DROP DATABASE db_rover;

CREATE DATABASE db_rover;

CREATE USER 'raspirover' IDENTIFIED BY 'raspirover';

GRANT USAGE ON *.* TO 'raspirover'@localhost IDENTIFIED BY 'raspirover';

GRANT ALL privileges ON `db_rover`.* TO 'raspirover'@localhost;

FLUSH PRIVILEGES;

SHOW GRANTS FOR 'raspirover'@localhost;     

USE db_rover;

CREATE TABLE IF NOT EXISTS EXPLORATION (
  exp_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(40) UNIQUE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS SENSOR (
  sen_id INT(11) NOT NULL PRIMARY KEY,
  fk_exp INT(11),
  type VARCHAR(25) DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_exp) REFERENCES EXPLORATION(exp_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS MQ2 (
  mq2_id INT(11) PRIMARY KEY,
  value VARCHAR(8) DEFAULT NULL,
  FOREIGN KEY (mq2_id) REFERENCES SENSOR(sen_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS LDR (
  ldr_id INT(11) PRIMARY KEY,
  value VARCHAR(8) DEFAULT NULL,
  FOREIGN KEY (ldr_id) REFERENCES SENSOR(sen_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

select * from mq2, sensor  where sen_id = 1;

