DROP DATABASE db_rover;

CREATE DATABASE db_rover;

CREATE USER 'raspirover' IDENTIFIED BY 'raspirover';

GRANT USAGE ON *.* TO 'raspirover'@localhost IDENTIFIED BY 'raspirover';

GRANT ALL privileges ON `db_rover`.* TO 'raspirover'@localhost;

FLUSH PRIVILEGES;

SHOW GRANTS FOR 'raspirover'@localhost;     

USE db_rover;

CREATE TABLE IF NOT EXISTS EXPLORATION (
  exp_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(40) UNIQUE,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS MQ2 (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_exp INT(11),
  value VARCHAR(8) DEFAULT NULL,
  type VARCHAR(25) DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_exp) REFERENCES EXPLORATION(exp_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS LDR (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_exp INT(11),
  value VARCHAR(8) DEFAULT NULL,
  type VARCHAR(25) DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_exp) REFERENCES EXPLORATION(exp_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS FIRE (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_exp INT(11),
  value VARCHAR(8) DEFAULT NULL,
  type VARCHAR(25) DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_exp) REFERENCES EXPLORATION(exp_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS HCSR04 (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_exp INT(11),
  value VARCHAR(8) DEFAULT NULL,
  type VARCHAR(25) DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_exp) REFERENCES EXPLORATION(exp_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS DHT22 (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  fk_exp INT(11),
  temp VARCHAR(8) DEFAULT NULL,
  hum VARCHAR(8) DEFAULT NULL,
  type VARCHAR(25) DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (fk_exp) REFERENCES EXPLORATION(exp_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

select dht22.temp, exploration.name 
from dht22, exploration
where exp_id ='14';


CREATE VIEW EXPLORATIONS AS
SELECT EXPLORATION.NAME, LDR.VALUE AS LDR, MQ2.VALUE AS MQ2, FIRE.VALUE AS FIRE, 
DHT22.TEMP AS DHT22TEMP, DHT22.HUM AS DHT22HUM
FROM EXPLORATION, MQ2, LDR, FIRE, DHT22, HCSR04
WHERE EXPLORATION.EXP_ID = MQ2.FK_EXP 
AND EXPLORATION.EXP_ID = LDR.FK_EXP
AND EXPLORATION.EXP_ID = FIRE.FK_EXP
AND EXPLORATION.EXP_ID = DHT22.FK_EXP
GROUP BY EXPLORATION.NAME, LDR.VALUE, MQ2.VALUE, FIRE.VALUE, DHT22.TEMP, DHT22.HUM;


CREATE VIEW EXPLO AS
SELECT EXPLORATION.NAME, MQ2.VALUE AS MQ2, DHT22.HUM AS DHT22HUM
FROM EXPLORATION, MQ2, DHT22
WHERE EXPLORATION.EXP_ID = MQ2.FK_EXP 
AND EXPLORATION.EXP_ID = DHT22.FK_EXP
GROUP BY EXPLORATION.NAME, MQ2.VALUE, DHT22.TEMP;

